sources:
  github:
    - url: "https://github.com/example/auth-system"
      type: "authentication"
      priority: high
      scan_interval: "1h"
      last_scanned: null

  youtube:
    - channel: "TechLead"
      type: "architecture"
      priority: medium
      scan_interval: "6h"
      last_scanned: null

  documentation:
    - url: "https://docs.example.com"
      type: "api"
      priority: low
      scan_interval: "24h"
      last_scanned: null

configuration:
  default_scan_interval: "1h"
  max_concurrent_scans: 5
  rate_limit_per_minute: 10
